### ISSUE TITLE
bug: when opening a single tab Edge instance, it opens File Explorer

### ISSUE THREAD

**Issue by ylluminate** [webcatalog/chromeless#14]
When starting an instance of Edge on Windows 10 with Chromeless 1.3 I'm finding that Explorer.exe is opened instead of an instance of Edge. Have you seen this before? Is there a way I can trace out how this is happening?

**Comment by quanglam2807** [comment]
Could you check where the shortcut of the app points to? If you can share the whole target path of the shortcut, it'd help a lot.
![relative-windows-shortcut](https://user-images.githubusercontent.com/1548835/120921136-76a46980-c6ec-11eb-941f-ddebd59e2b39.png)

**Comment by quanglam2807** [comment]
Due to difficulties in maintaining the app on Windows, we've decided to drop Windows support in v2.x. So I'm sorry that we won't able to resolve this.
