### ISSUE TITLE
bug: Google prevents logging in

### ISSUE THREAD

**Issue by moontan** [webcatalog/chromeless#34]
# Bug Report
**Specifications:**
- App Version: 1.4.0
- OS (macOS, Windows, Linux): macOS 11.4

**Description:**
With any of the Google products from the catalog after installing as Chrome- or Chromium-based SSB the Google login will refuse to let the user enter their password, stating the browser environment isn't secure.

**Steps to Reproduce:**
Install any Google product from the catalog and try to log in with a google account's credentials.

**Additional Context**

**Comment by quanglam2807** [comment]
Working on a fix.

**Comment by cdeutsch** [comment]
I'm running into this issue today.

Everything worked a month or so ago.
