### ISSUE TITLE
feature: Migrate WebCatalog Non-Elektron Engine Apps

### ISSUE THREAD

**Issue by scottrbaxter** [webcatalog/chromeless#4]
# Feature Request
**Specifications:**
- App Version:
- OS (macOS, Windows, Linux):

**Description:**

I've got a ton of custom apps that I've curated over time, naming/urls/icons/various engines... long ago I built a template per backend engine to make things easier for setting up a new custom app, though this requires manually replacing the newly created folder under `ChromiumProfiles`, it does indeed work fine. Upon updating WebCatalog to v31 and finding out about Chromeless, I was able to bring along my engine Template, just as I was able per each WebCatalog app (excellent!).

That said, I've got a bunch of apps, and would prefer to not have to one-by-one go into WebCatalog, screenshot `View Details`, remove the app, then install new custom app in Chromeless, following my previous config. Any chance there's a rather easy way to _migrate_ any/all WebCatalog custom apps over to Chromeless? Would save me a ton of time. Btw, thanks for making Chromeless and not just deprecating features that don't 100% line up with your WebCatalog roadmap!

Cheers!

**Comment by quanglam2807** [comment]
Thank you for bringing this up, @scottrbaxter.

Have you tried simply moving the apps from `WebCatalog Apps` directory to `Chromeless Apps`?  And then move the entire `ChromiumProfiles` from `WebCatalog/ChromeProfiles` to `Chromeless/ChromeProfiles`?

**Comment by quanglam2807** [comment]
Btw, I don't think you really need to migrate the apps. They will continue working just fine.

**Comment by scottrbaxter** [comment]
Thanks @quanglam2807! Didn't realize it would be as easy as copying/moving the `App Name.app` along with the corresponding `ChromeProfiles` folder.

For clarity if anyone else is interested, `View Details` on the app within WebCatalog to find the `Related Files and Directories`. This was for macOS.
```
cp -a ~/Application/WebCatalog\ Apps/<app_name>.app ~/Application/Chromeless\ Apps/<app_name>.app
cp -a ~/Library/Application Support/WebCatalog/ChromiumProfiles/<app_folder> ~/Library/Application Support/Chromeless/ChromiumProfiles/<app_folder>
```

As for not needing to migrate, I wasn't sure if they would eventually stop working in WebCatalog... all the warning icons worried me a bit, so I figured I aught to get apps moved over ASAP, to avoid further troubleshooting when I really need an app up and running.

**Comment by quanglam2807** [comment]
My bad, Scott. I forgot to mention an additional step. After moving, you’ll need to use the “Repair” feature in Chromeless to correctly point the app to the new ChromeProfiles folder. If not, those apps will still use the old ChromeProfile in WebCatalog directory.

**Comment by quanglam2807** [comment]
I just made it simpler for you. After moving the apps to `Chromeless Apps` directory. Just open Chromeless 1.1.0+ and update all the apps.

**Comment by quanglam2807** [comment]
Btw, this will only work with Chromium-based apps, not Firefox-based or WebKit-based apps.

**Comment by scottrbaxter** [comment]
> I just made it simpler for you. After moving the apps to `Chromeless Apps` directory. Just open Chromeless 1.1.0+ and update all the apps.

Thanks! I noticed the update this morning, though I did move and test several apps yesterday without needing the Repair feature. I did remove all apps from WebCatalog that I added to Chromeless already, though there was some overlap with my testing... so not sure exactly when I would have needed to "Repair". Either way, it's working fine for me!

Side note, upon updating to 1.1.0 today, I did notice that any app I open, I need to click "open" a 2nd time, to get it to run. Same goes for opening an app in Finder, or using Spotlight/Alfred to launch them. It's a one-time event, but does happen. I've noticed it periodically with WebCatalog, though felt like low-hanging fruit, so I hadn't reported it yet. Not sure if you know what causes that, but I  if I copy over a (e.g. Brave browser) template upon creating a new app, I need to "open" the app twice on first boot, every time. No big deal, just though I'd mention it in case you had any ideas. I can submit a formal issue for that, if you prefer.

**Comment by quanglam2807** [comment]
> > I just made it simpler for you. After moving the apps to `Chromeless Apps` directory. Just open Chromeless 1.1.0+ and update all the apps.
> 
> Thanks! I noticed the update this morning, though I did move and test several apps yesterday without needing the Repair feature. I did remove all apps from WebCatalog that I added to Chromeless already, though there was some overlap with my testing... so not sure exactly when I would have needed to "Repair". Either way, it's working fine for me!

That's great! But I think if you move the apps to the new folder, they'll work normally. But they will use the the old `ChromeProfiles` paths, `Repair` would correct that. But if that didn't occur to you then honestly I don't know how. :d 

> Side note, upon updating to 1.1.0 today, I did notice that any app I open, I need to click "open" a 2nd time, to get it to run. Same goes for opening an app in Finder, or using Spotlight/Alfred to launch them. It's a one-time event, but does happen. I've noticed it periodically with WebCatalog, though felt like low-hanging fruit, so I hadn't reported it yet. Not sure if you know what causes that, but I if I copy over a (e.g. Brave browser) template upon creating a new app, I need to "open" the app twice on first boot, every time. No big deal, just though I'd mention it in case you had any ideas. I can submit a formal issue for that, if you prefer.

Thank you for bringing this up, Scott. I managed to reproduce it. It looks like a Big Sur related bug
```
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10827 "kLSNoExecutableErr: The executable is missing" UserInfo={_LSLine=3665, _LSFunction=_LSOpenStuffCallLocal}
```
