### ISSUE TITLE
bug: All existing and new chromeless apps Fail to Start

### ISSUE THREAD

**Issue by jmdilley** [webcatalog/chromeless#40]
# Bug Report
**Specifications:**
- App Version: 1.6.0
- OS (macOS, Windows, Linux): macOS 11.4

**Description:**
Earlier today running Chromeless apps were fine.  Due to another issue, I had to reboot my Mac and after doing so no Chromeless apps will launch.  They will sometimes display an error "Failed to load extension from: . Manifest file is missing or unreadable", and sometimes they won't display anything, they simply show on the Dock but have no application window.

**Steps to Reproduce:**
I can not launch any existing apps, or create a new one.  I've chosen Vivaldi and Microsoft Edge as the engines, with the same result.

**Additional Context**

![chromeless-launch-error](https://user-images.githubusercontent.com/11199091/122113433-bbfd2100-cde7-11eb-93bb-59ed1200c0b3.png)

**Comment by quanglam2807** [comment]
This bug is critical. Could you compress one of the app as ZIP and share with us? You can upload it here or email us via help@webcatalog.app

**Comment by quanglam2807** [comment]
Actually, I've managed to reproduce the bug. Update will be available soon to fix this.

**Comment by quanglam2807** [comment]
@jmdilley I've pushed v1.6.1. It should fix the bug.

**Comment by jmdilley** [comment]
Thanks!  Yes, my apps now launch once updated.  Only problem is all history and bookmarks are gone, which is a bummer, but I can set those back up.

**Comment by quanglam2807** [comment]
I'm so sorry, @jmdilley. It's likely that the app data folder was pointed to somewhere else earlier because of the bug.
