### ISSUE TITLE
feature: configure Chromeless.app icon

### ISSUE THREAD

**Issue by scottrbaxter** [webcatalog/chromeless#42]
# Feature Request
**Specifications:**
- App Version: 1.4.0+
- OS (macOS, Windows, Linux): macOS, but this should apply to all platforms

**Description:**

The Chromeless.app icon [changed](https://github.com/webcatalog/chromeless/pull/28) with the `v1.4.0` release. I prefer the look of the previous icon before the rebranding images change. I checked under Preferences/Appearance for an option to revert, but only found Light/Dark themes for inside the app itself. Would you mind adding an Appearance feature to use the previous icon, and/or perhaps a custom icon provided by the user?

**Comment by quanglam2807** [comment]
Do you mean the default app icon for custom app or the icon of the Chromeless app itself, Scott?

**Comment by scottrbaxter** [comment]
Sorry, I referenced the default app icon for created apps within Chromeless, but yes, I do mean the Chromeless.app icon itself. I've updated the description with 1.4.0, and the rebranding PR with the new icons. Sorry for the confusion.

**Comment by quanglam2807** [comment]
Thank you, @scottrbaxter. I personally dislike the old icon. Honestly, it's so hard to find something that represents Chromeless well. Do you any suggestions?

**Comment by quanglam2807** [comment]
After staring at the icon for a while, I have to admit it looks ugly. Will try to find a replacement ASAP.
