### ISSUE TITLE
bug: WebKit apps can no longer be installed.

### ISSUE THREAD

**Issue by LonWake** [webcatalog/chromeless#55]
# Bug Report
Chromeless v1.6.1
macOS Big Sur v11.5

**Description:**
Can no longer create new apps using the WebKit (part of Safari) browser engine.  It throws off an error of "Failed to install iCloud Reminders".  The same app can be created using another browser, such as Google Chrome.  This behavior so far is only observed when selecting the WebKit engine.

<img width="853" alt="Screen Shot 2021-07-30 at 9 36 59 AM" src="https://user-images.githubusercontent.com/63072349/127684328-9efd926e-bd3f-4319-895f-e9af33bc5d3c.png">

**Comment by quanglam2807** [comment]
Thanks for reporting! It's a backend bug. Fixed.
