### ISSUE TITLE
bug: App "View Details" is missing

### ISSUE THREAD

**Issue by scottrbaxter** [webcatalog/chromeless#58]
# Bug Report
**Specifications:**
- App Version: v2.0.0
- OS (macOS, Windows, Linux): macOS Big Sur

**Description:**

View Details used to exist, and i used it as a reference for the location of the ChromeProfiles path, as I'd regularly copy the folder for Chromium/Brave/Vivaldi settings/extensions from one app to another. It had gone missing in recent versions and is still not there in the current latest: v2.0.0.

**Steps to Reproduce:**

1. Open Chromeless.app
2. Click Updates tab on bottom of app
3. Click any app's hamburger menu
4. Secondary window no longer has an option that shows the path to the folder in `~/Library/Application Support/Chromeless/ChromiumProfiles/...`
 
**Additional Context**

Here's the image from a the older 1.2.0 version:
<img width="296" alt="Screen Shot 2021-08-05 at 6 34 38 PM" src="https://user-images.githubusercontent.com/4142806/128437158-affd7540-8e37-44b4-b043-4a70612b0841.png">
Here's the image from v2.0.0:
<img width="288" alt="Screen Shot 2021-08-05 at 7 16 24 PM" src="https://user-images.githubusercontent.com/4142806/128437177-09e3760e-5b13-47bd-93b8-7b26132f1d76.png">

If you don't want to keep View Details in this menu, could you please make an easy way to reference the path to the Library folder for each specific app?

**Comment by quanglam2807** [comment]
My bad, Scott. I removed the dialog without considering this. I'll recover it in the next update.

**Comment by scottrbaxter** [comment]
No worries, but thanks for the quick follow-up! Ultimately all i'd like is an easy/quick reference to the data location, so i can easily determine which folder matches the app that i just created. oddly enough, opening Chromeless touches several folders in `~/Library/Application Support/Chromeless/ChromiumProfiles/`, so even `ls -lt` to sort by latest isn't actually consistently accurate. Without the details in the app, I guess the next best thing is to `jq .id /path/to/app.asar.unpacked/build/app.json`... at least that seems to be the easiest means i've come across. 🙃

I don't recall exactly what was in the View Details page, as I hadn't created a new app for a while now... but if you wanted to simplify it by just adding an "open data folder" in this hamburger menu to simply open this path in the OS file manager, that'd be fine too. Thanks again for the great app!

**Comment by scottrbaxter** [comment]
Thanks for knocking this out so quickly, @quanglam2807!
