### ISSUE TITLE
bug: Switching to a running app from the macOS dock opens a new tabbed window

### ISSUE THREAD

**Issue by chrisminett** [webcatalog/chromeless#59]
# Bug Report
**Specifications:**
- App Version: 2.0.0
- OS (macOS, Windows, Linux): macOS 11.5.1
- Google Chrome: 92.0.4515.131

**Description:**
Clicking the doc icon for an open Chromeless app, using the Chrome engine, opens a blank Chrome window. Previously it would give the expected behaviour of opening the existing window. I'm running v2.0.0 but the issue occurred before updating to that version (I'm unsure exactly when this started).

**Steps to Reproduce:**
- Open a Chromeless app, e.g. Google Meet, which runs the Google Chrome engine in a tabless mode.
- The site is shown in a window.
- Switch to any other app.
- Click the running dock icon for the Chromeless app; the Chromeless app is brought to the foreground and opens a new tabbed browser window over the existing open window. Shutting the new tabbed window shows the existing window behind.

**Additional Context**
Switching to the open Chromeless app using Cmd+Tab shows the existing window without opening a new tabbed window as expected. The unexpected behaviour only happens when clicking the running app from the dock.

_New issue created from https://github.com/webcatalog/chromeless/issues/20#issuecomment-896718029_

**Comment by quanglam2807** [comment]
A fix will be available shortly. It's not really a perfect fix. Chromeless simply detects if Chrome opens the unwanted window and closes it immediately. I don't know how to prevent it from opening.

**Comment by chrisminett** [comment]
Fix works, although I see what you mean about imperfect fix, as it's sometimes possible to *briefly* see the new window attempt to open before it's closed (few ms only though, no big deal!). Thank you!

The doc does seem to be an odd thing. When using [Epichrome](https://github.com/dmarmor/epichrome), the app in the dock was the Epichrome app, but with Chromeless it seems that the app in the dock is actually another app within the Chromeless app, i.e. `/Applications/Chromeless Apps/{name-of-app}.app/Content/Resources/{name-of-app}.app`. I wonder if this disparity with what macOS sees as the running app also impacts the permissions issue in #22 .
