### ISSUE TITLE
Clicking App Icon in OS X Dock opens a new Brave window instead of focusing the already open Brave window with the SSB

### ISSUE THREAD

**Issue by anthonysapien** [webcatalog/chromeless#64]
I did the following:

1. Create a Brave-based SSB for a website (Single-app, standard, no tabs)
2. Add the app to my OS X dock
3. Open the app. All good!
4. Tab to another app.
5. Click the app icon in the Dock to bring it back into focus.
6. A new blank Brave tab opens
7. My app is still open, but not focused and I have to close this blank Brave tab.

Please let me know if you need anything else.
Thanks!

**Comment by quanglam2807** [comment]
Thanks for reporting. Same as https://github.com/webcatalog/chromeless/issues/59. The bug has been fixed in the latest version.

**Comment by anthonysapien** [comment]
It's working for me in 2.1. Thank you!
