### ISSUE TITLE
bug: On Ubuntu 18, Firefox is not listed as Browser Engine when installing an app

### ISSUE THREAD

**Issue by ameliorate-droid** [webcatalog/chromeless#9]
# Bug Report
**Specifications:**
- App Version: 1.3.0
- OS (macOS, Windows, Linux): Ubuntu 18.04.5 LTS

**Description:**

When installing an app, Firefox is not listed as an option in the Browser Engine list.

**Steps to Reproduce:**

1. Open Chromeless
2. Choose any app from "Catalog"
3. Click on "INSTALL"
4. In the list of Browser Engine, Firefox is not available

**Additional Context**

![chromeless-1](https://user-images.githubusercontent.com/52375566/115084272-f9f6d980-9f4b-11eb-8a7a-3adbd6d13380.png)

**Comment by quanglam2807** [comment]
I don't remember the exact reason but it's not there because I couldn't figure out a way to make Firefox work with this app.
